from app.models.ai import AIConversation, AIInsight, AIMessage, Job, MemoryDocument, RateLimitHit, Receipt, StoredFile
from app.models.base import Base
from app.models.identity import AuthToken, Session, User, UserSettings
from app.models.ledger import (
    Account,
    Category,
    ImportBatch,
    Merchant,
    Tag,
    Transaction,
    TransactionItem,
    transaction_tags,
)
from app.models.planning import (
    Budget,
    BudgetCategory,
    Debt,
    DebtPayment,
    FinancialNote,
    GoalContribution,
    MoneyPlan,
    PlannedPurchase,
    RecurringPayment,
    SavingsGoal,
)

__all__ = [
    "AuthToken",
    "RateLimitHit",
    "StoredFile",
    "AIConversation",
    "AIInsight",
    "AIMessage",
    "Account",
    "Base",
    "Budget",
    "BudgetCategory",
    "Category",
    "Debt",
    "DebtPayment",
    "FinancialNote",
    "GoalContribution",
    "ImportBatch",
    "Job",
    "MemoryDocument",
    "Merchant",
    "MoneyPlan",
    "PlannedPurchase",
    "Receipt",
    "RecurringPayment",
    "SavingsGoal",
    "Session",
    "Tag",
    "Transaction",
    "TransactionItem",
    "User",
    "UserSettings",
    "transaction_tags",
]

USER_SCOPED_TABLES = [
    "user_settings",
    "accounts",
    "categories",
    "merchants",
    "tags",
    "transactions",
    "transaction_items",
    "budgets",
    "budget_categories",
    "savings_goals",
    "goal_contributions",
    "recurring_payments",
    "debts",
    "debt_payments",
    "financial_notes",
    "receipts",
    "embeddings",
    "ai_insights",
    "ai_conversations",
    "ai_messages",
    "stored_files",
    "planned_purchases",
    "money_plans",
    "import_batches",
]
